/* 3D Muse word banks.
   Loaded as a plain global so it works when opening index.html directly
   from disk (file://) without a server. index.html reads window.MUSE_DATA.
   Add lines freely - each category is just an array of strings (ASCII only). */
window.MUSE_DATA = {
    subject: [
        "Ancient warrior", "Cybernetic being", "Mystic creature", "Clockwork droid",
        "Ethereal spirit", "Alien wanderer", "Astronaut", "Minotaur", "Forest guardian",
        "Rogue android", "Sea witch", "Desert nomad", "Fallen angel", "Ghost samurai",
        "Crystal golem", "Void priestess", "Storm elemental", "Plague doctor",
        "Deep-sea diver", "Time traveler", "Dragon rider", "Shadow assassin",
        "Celestial knight", "Swamp hag", "Lunar monk", "Frost giant", "Carnival jester",
        "Bog troll", "Star cartographer", "Mecha pilot", "Tribal shaman", "Vampire lord",
        "Junkyard scavenger", "Oracle child", "Iron golem", "Coral mermaid",
        "Wasteland ranger", "Court alchemist", "Phantom knight", "Insectoid queen",
        "Cloud nomad", "Grave keeper", "Solar engineer", "Feral werewolf",
        "Porcelain doll", "Mountain hermit", "Neon street racer", "Sand serpent",
        "Beast tamer", "Hollow puppet",
        "Power-armor soldier", "Tank commander", "Special forces operative",
        "Battle-mech pilot", "Sniper", "Demolitions expert", "Fighter ace",
        "Drone operator", "War machine", "Heavy gunner", "Mercenary captain",
        "Riot trooper", "Naval admiral", "Bomb-disposal robot", "Frontline medic",
        "Cyborg commando", "Artillery officer", "Recon scout", "Siege engineer",
        "Exo-suit marine",
        // ---- additional subjects ----
        "Abyssal leviathan", "Cinder wraith", "Dune stalker", "Fungal druid",
        "Gear-mage", "Hive mind drone", "Iron saint", "Jade serpent", "Kraken tamer",
        "Lightweaver", "Mirror double", "Nightmare steed", "Obsidian gargoyle",
        "Paper lantern spirit", "Quicksilver mimic", "Rust angel", "Soul merchant",
        "Tendril beast", "Umbral assassin", "Venom tongue", "Whispering mask",
        "Xenobiologist", "Yarn golem", "Zen archer", "Arcane trickster", "Bone collector",
        "Candle keeper", "Drowned sailor", "Echoing specter", "Flame dancer",
        "Gilded automaton", "Horned hunter", "Icy shaman", "Junk mage", "Kite flyer",
        "Lava surfer", "Magnetic drifter", "Necrotic knight", "Orrery priest",
        "Petrified king", "Quake herald", "Rift walker", "Sage of thorns",
        "Tattooed mystic", "Unstable clone", "Vortex spawn", "Wind caller",
        "Xylophone skeleton", "Yeti hermit", "Zombie botanist"
    ],
    object: [
        "Holocron", "Relic", "Amulet", "Mechanical heart", "Plasma sword", "Ancient crown",
        "Power core", "Puzzle cube", "Lantern", "Compass", "Mask", "Quill", "Hourglass",
        "Throne", "Music box", "Grimoire", "Skull totem", "Floating orb", "War banner",
        "Crystal staff", "Broken sword", "Pocket watch", "Spell scroll", "Iron key",
        "Singing bell", "Severed hand", "Glass eye", "Rune stone", "Coil engine",
        "Tarot deck", "Cursed ring", "Star map", "Bone flute", "Reactor cell",
        "Astrolabe", "Chalice", "Gas mask", "Spirit jar", "Anchor", "Gauntlet",
        "Prism shard", "Wind chime", "Battle drum", "Telescope", "Locket",
        "Obsidian dagger", "Brass gear", "Vial of light", "Folded fan", "Caged firefly",
        "Ammo crate", "Dog tags", "Field radio", "Riot shield", "Ration tin",
        "Targeting visor", "Grappling hook", "Detonator", "Supply drop", "Combat knife",
        "Med kit", "Smoke grenade", "Spent shell casing", "Jerry can", "Gas canister",
        // Weapons
        "Plasma rifle", "Railgun", "Revolver", "Assault rifle", "Sniper rifle",
        "Rocket launcher", "Gatling gun", "Laser cannon", "Pump shotgun", "Combat shotgun",
        "Submachine gun", "Flamethrower", "Grenade launcher", "Crossbow", "War hammer",
        "Katana", "Chainsword", "Battle axe", "Energy blade", "Gauss cannon",
        "Minigun", "Pulse pistol", "Sawed-off shotgun", "Halberd", "Bo staff",
        "Throwing knife", "Sniper crossbow", "BFG cannon", "Dual pistol", "Tesla coil gun",
        "Heavy machine gun", "Sticky bomb", "Plasma grenade", "Arc welder", "Cryo blaster",
        "Scoped carbine", "Bayonet rifle", "Spear", "Morning star", "Disc launcher",
        "Coilgun", "Flak cannon", "Nail gun", "Harpoon gun", "Beam saber",
        "Longbow", "Mace", "Rapier", "Trench knife", "Revolver rifle",
        "Stun baton", "Riot gun", "Hand cannon", "Bolt-action rifle", "Greatsword",
        // Vehicles
        "Battle tank", "Gunship", "Stealth jet", "Mech walker", "Hover bike",
        "Armored truck", "Attack helicopter", "Submarine", "Dropship", "Dune buggy",
        "APC", "Battleship", "Recon drone", "Jet fighter", "Monster truck",
        "Spider tank", "Hovercraft", "Speeder bike", "Bomber plane", "Motorcycle",
        "Half-track", "Self-propelled gun", "Sci-fi cruiser", "Walker mech", "Stealth bomber",
        "Patrol boat", "Cargo hauler", "Quad bike", "Rail cannon platform", "Assault chopper",
        "Excavator rig", "Ironclad", "Forklift", "Siege ram", "Escape pod",
        // ---- additional objects ----
        "Abacus", "Barometer", "Catacomb key", "Divination coin", "Entropy lens",
        "Fossilized egg", "Gravity anchor", "Holographic diary", "Incense burner",
        "Jar of souls", "Kinetic pendulum", "Lunar dial", "Magnetic clamp", "Nebula orb",
        "Ocarina of time", "Phylactery", "Quantum spool", "Rusted bell", "Sanguine vial",
        "Tesseract frame", "Undertaker's shovel", "Void compass", "Weeping statue",
        "Xylograph plate", "Yantra wheel", "Zen garden rake", "Abyssal pearl",
        "Bone saw", "Clockwork spider", "Desiccated heart", "Echo shell",
        "Frozen tear", "Graviton sphere", "Husk of a locust", "Iron lung",
        "Jigsaw box", "Kinetic scythe", "Lament configuration", "Mimic chest",
        "Necromantic bell", "Oil lamp (worn)", "Pinwheel of prophecy", "Quarantine seal",
        "Rune-etched femur", "Shattered covenant", "Tallow candle", "Umbral urn",
        "Vortex stabilizer", "Warp whistle", "Xenomorph egg", "Yarn ball of fate",
        "Zero-point filament", "Anvil of stars", "Blood thermometer", "Crown of thorns",
        "Drainpipe organ", "Ember rod", "Fey contract", "Gear of aeons", "Harp of ruin"
    ],
    style: [
        "Art Deco", "Cyberpunk", "Steampunk", "Low Poly", "Hyper-realistic", "Gothic",
        "Brutalist", "Biopunk", "Vaporwave", "Solarpunk", "Baroque", "Minimalist",
        "Surrealist", "Dieselpunk", "Cel-shaded", "Claymation", "Art Nouveau",
        "Pixel art", "Stained glass", "Origami", "Wireframe", "Voxel", "Papercraft",
        "Glitch art", "Tribal", "Cosmic horror", "Toy figurine", "Marble sculpture",
        "Neo-noir", "Retro 80s", "Ukiyo-e", "Cubist", "Photoreal PBR", "Hand-painted",
        "Chrome liquid", "Crystalline", "Tron-style", "Mosaic", "Woodcut", "Inflatable",
        "Knitted yarn", "Sandstone carving", "Holographic", "Ink wash", "Bauhaus",
        // ---- additional styles ----
        "Acidwave", "Afrofuturism", "Alien biosphere", "Ancient Greek pottery", "Atompunk",
        "Boho chic", "Bone china", "Cardboard cutout", "Cartoon network", "Chalk pastel",
        "Clippy (paper doll)", "Cold War propaganda", "Collage", "Color field", "Concrete",
        "Constructivist", "Corrugated iron", "Crayon sketch", "Crosshatch", "Crystal punk",
        "Cutout animation", "Dark academia", "Data moshing", "Deconstructivist", "Diamond armor",
        "Doodle", "Dot matrix", "Dripping paint", "Dry brush", "Dust jacket", "Eco brutalist",
        "Egyptian frieze", "Embroidery", "Enamel pin", "Engraving", "Escher tessellation",
        "Fairy tale illustration", "Fauvist", "Felt fabric", "Fiber art", "Film grain",
        "Folk art", "Fresco", "Frosted glass", "Futurist", "Gel printing", "Geometric abstraction",
        "Gingerbread", "Glassblown", "Glossy magazine", "Gouache", "Graffiti tag",
        "Grunge", "Hair embroidery", "Halftone", "Hatching", "Heavy metal album",
        "Holographic sticker", "Impasto", "Isometric", "Jade carving", "Jugendstil",
        "Kinetic sand", "Lacquerware", "Laser cut", "Lavender and lace", "Leather tooling",
        "Lichen and moss", "Light field", "Line art", "Lithophane", "Loom beading",
        "Low relief", "Luminogram", "Macrame", "Mandala", "Marble cake", "Matte painting",
        "Maya relief", "Melted wax", "Meteorite polish", "Milk glass", "Misty gradient",
        "Monoprint", "Mosaic tile", "Nail art", "Needlepoint", "Neon sign", "Nouveau rustic",
        "Oil slick", "Ooze", "Op art", "Origami paper", "Overprint", "Patchwork", "Pebble mosaic",
        "Pencil sketch", "Phong shading", "Plastic toy", "Polaroid", "Poly pocket", "Pop art",
        "Porcelain", "Poster art", "Psychedelic", "Pumice stone", "Puppet theater", "Quilted",
        "Radial gradient", "Raku pottery", "Raster scan", "Recursive fractal", "Repousse",
        "Ribbon embroidery", "Rococo", "Rorschach", "Rug hooking", "Rustic log", "Satin finish",
        "Scrimshaw", "Sgraffito", "Shag carpet", "Shiny chrome", "Shoegaze haze", "Shou sugi ban",
        "Silhouette", "Silk painting", "Slime texture", "Smoky quartz", "Soft pastel",
        "Spray paint", "Stencil", "Stippling", "Stone wash", "String art", "Stylized vector",
        "Sumi-e", "Sun bleaching", "Swarovski crystal", "Tactile bumps", "Tatami mat",
        "Taxidermy", "Terra cotta", "Thatched roof", "Thermochromic", "Tie-dye",
        "Tin toy", "Tinsel", "Toon shaded", "Tramp art", "Transparent plastic",
        "Trompe l'oeil", "Tweed fabric", "Twisted metal", "Ukiyo-e woodblock",
        "Unfinished sketch", "Upholstery velvet", "Varnish drip", "VHS tracking",
        "Victorian scrapbook", "Video feedback", "Watercolor bloom", "Wax seal",
        "Weathered wood", "Weeping willow", "Wet concrete", "Whittled", "Wicker weave",
        "Wire sculpture", "Wool felt", "Woven basket", "Xerox art", "Yarn bombing",
        "Zentangle", "Zinc printing"
    ],
    era: [
        "Digital era 2040", "Bronze Age", "Victorian era", "Year 3000", "Post-apocalyptic",
        "Renaissance", "Edo period", "Stone Age", "Roaring Twenties", "Far future",
        "Medieval", "Atomic Age", "Ice Age", "Industrial Revolution", "Space Age",
        "Wild West", "Ancient Egypt", "Byzantine empire", "Cold War", "Belle Epoque",
        "Pre-historic", "Iron Age", "Golden Age of Piracy", "Neo-Tokyo 2099",
        "Dawn of mankind", "Age of Sail", "Information Age", "Dieselpunk 1940s",
        "Dark Ages", "Mythic antiquity", "Cyber-future 2200", "Colonial era",
        "Jurassic period", "Distant collapse", "Feudal Japan",
        // ---- additional eras ----
        "Age of Discovery", "Age of Aquarius", "American Revolution", "Anglo-Saxon",
        "Antebellum South", "Arthurian legend", "Aztec empire", "Babylonian", "Beaker culture",
        "Bell Beaker", "Black Death years", "Belle Epoque", "Byzantine golden age",
        "Cambrian explosion", "Carolingian", "Cenozoic", "Chalcolithic", "Charlemagne's reign",
        "Cretaceous", "Crusader states", "Deco 1930s", "Devonian", "Early Christian",
        "Early modern", "Edwardian", "Eocene", "Etruscan", "Franco-Prussian war",
        "Gilded Age", "Gojoseon", "Goryeo dynasty", "Great Depression", "Habsburg Spain",
        "Hallstatt culture", "Hellenistic", "Hittite empire", "Holocene", "Hungarian revolution",
        "Inca empire", "Interwar period", "Jazz Age", "Joseon dynasty", "Jurassic (late)",
        "Khmer empire", "La Tene culture", "Late antiquity", "Little Ice Age", "Long 19th century",
        "Magdalenian", "Mali empire", "Mayan classic", "Merovingian", "Mesolithic",
        "Middle kingdom Egypt", "Migration period", "Ming treasure voyages", "Mississippian",
        "Modernist 1920s", "Mughal empire", "Mycenaean", "Napoleonic wars", "Neolithic",
        "New kingdom Egypt", "Norman conquest", "Old kingdom Egypt", "Oligocene", "Ottoman peak",
        "Paleocene", "Paleolithic", "Permian", "Phoenician", "Pleistocene", "Pliocene",
        "Pre-Columbian", "Prohibition", "Proto-Renaissance", "Ptolemaic", "Qin dynasty",
        "Reconstruction era", "Regency era", "Restoration period", "Revolutionary France",
        "Roman empire peak", "Roman republic", "Sasanian", "Sengoku period", "Showa early",
        "Silurian", "Song dynasty", "Spanish golden age", "Steppe empires", "Sumerian",
        "Taisho era", "Tang dynasty", "Tudor period", "Triassic", "Troubles (Ireland)",
        "Ur III dynasty", "Viking age", "Warring states", "Western Jin", "Xia dynasty",
        "Yuan dynasty", "Zhou dynasty", "Zuni pueblo"
    ],
    flavor: [
        "bioluminescent veins", "glowing runes", "weathered metal", "floating fragments",
        "tarnished gold", "ice crystals", "molten cracks", "dripping moss",
        "shattered glass", "neon circuitry", "rusted gears", "drifting embers",
        "creeping vines", "fractured stone", "swirling smoke", "frozen lightning",
        "blooming flowers", "torn fabric", "liquid mercury", "spreading rot",
        "static sparks", "barnacle crust", "spider silk", "cracked porcelain",
        "drifting ash", "wet clay", "polished chrome", "tangled wires",
        "crystallized sap", "scorched edges", "morning dew", "petrified wood",
        "iridescent scales", "dust motes", "bleeding ink", "frosted breath",
        "tar and feathers", "glittering sand", "leaking coolant", "honeycomb patterns",
        // ---- additional flavors ----
        "abyssal ink", "acrid fumes", "alien pollen", "amber inclusions", "ancient moss",
        "angelic feathers", "arcane circuitry", "ashen soot", "astral dust", "ball lightning",
        "barbed wire", "beeswax drips", "black ichor", "blinding glare", "blood splatters",
        "blue vitriol", "boiling tar", "bone splinters", "brine crust", "brittle frost",
        "burnt gunpowder", "candle wax", "charred wood", "chattering teeth", "clay streaks",
        "coagulated milk", "cobwebs", "coffee stains", "copper patina", "corroded acid",
        "cracked glaze", "crimson threads", "crumbled plaster", "crystal warts", "cursed thorns",
        "cyan drips", "dangling charms", "dark star matter", "decayed lace", "dewdrop pearls",
        "diamond dust", "dried blood", "dried seaweed", "dripping honey", "echoing hum",
        "effervescent bubbles", "electric arc", "ember sparks", "engraved scars", "eroded grooves",
        "ethereal mist", "fading glow", "fairy circle", "fake fur", "falling petals",
        "false eyes", "fatty tissue", "feather burn", "fiery tendrils", "filigree vines",
        "fingerprint smudges", "firefly swarms", "flaking rust", "flare streaks", "flatworm slime",
        "flickering shadow", "floating dust", "flux residue", "foam bubbles", "fog droplets",
        "folding creases", "fossil impressions", "foul brine", "fractured mirror", "frost flowers",
        "frozen tears", "fruit flies", "fungal spots", "furry mold", "ghostly afterimage",
        "glass shards", "glossy resin", "gold leaf flaking", "grainy salt", "gravitational lensing",
        "grease stains", "gum bubbles", "hairline cracks", "halo rings", "hammered dents",
        "hanging threads", "hazy smoke", "heat shimmer", "heavy rust", "hole punches",
        "holographic confetti", "honey drips", "hot slag", "humming vibrations", "ice needles",
        "incense ash", "ink bleeds", "inner glow", "insect wings", "interference patterns",
        "jagged tears", "jelly wobble", "knife gouges", "lacquer drips", "lava bubbles",
        "leather burn", "lemon rind", "lichen spots", "light leaks", "lime scale",
        "liquid crystal", "luminous spores", "lunar dust", "magnetic field lines", "marble veins",
        "melted crayon", "metal burrs", "mica flakes", "micro cracks", "milk skin",
        "mirage ripple", "moldy fuzz", "moon crater", "moth scales", "mud cracks",
        "mummified wrap", "mushroom rings", "neon bleed", "oil slick rainbow", "opalescent film",
        "orange peel texture", "origami folds", "ozone smell (visual)", "paint drips",
        "parchment burn", "pearl essence", "peeling stickers", "petal veins", "phlegm blobs",
        "piano strings", "pierced holes", "pill indentations", "plasma arcs", "plaster patches",
        "plastic wrap crinkle", "pollen clouds", "polished edges", "porous pits", "powder smears",
        "prismatic flares", "pumice bubbles", "puzzle cuts", "pyrite flecks", "quartz veins",
        "radioactive shimmer", "rainbow sheen", "raised welts", "raspberry seeds", "ray dots",
        "rebar scars", "resin bubbles", "ribbon curls", "rice paper texture", "rivet bumps",
        "rocky nodules", "rope burns", "rose thorns", "rust blooms", "saffron powder",
        "sand grains", "scab ridges", "scorch marks", "scratched plastic", "screw threads",
        "serrated edges", "sewage sludge", "shattered enamel", "shaving cuts", "silk fibers",
        "silver tarnish", "sintered dust", "slimy film", "sludge drips", "smoke rings",
        "snowflakes", "soap bubbles", "soft fuzz", "soot stains", "sparkle trails",
        "spectral haze", "spider webs", "spiral arms", "splintered wood", "spongy pores",
        "spring coils", "sprouting seeds", "stardust", "static charge", "steam wisps",
        "sticky glue", "stone lichen", "straw bits", "stretched canvas", "stucco bumps",
        "sugar crystals", "sulphur patches", "sun flares", "sweat droplets", "tar streaks",
        "tattoo lines", "tear stains", "tendril curls", "terry cloth", "tinsel strips",
        "tooth marks", "translucent skin", "trash bags", "tree rings", "tumbleweed fuzz",
        "twinkling LED", "twisted fiber", "tyre treads", "uneven stitching", "urine stains",
        "varnish yellowing", "velvet nap", "vent holes", "verdigris crust", "vibrating strings",
        "violet glow", "warped vinyl", "wasp nests", "water beading", "wax drips",
        "weathered rope", "webbing strands", "wet ink", "whiskers", "whorls and spirals",
        "wind erosion", "wire brush marks", "wool pilling", "worm trails", "wrinkled paper",
        "xenon flash", "yellow cake", "yogurt splash", "zebra stripes", "zinc blooms"
    ],
    lighting: [
        "dramatic rim light", "soft volumetric haze", "harsh neon glow",
        "golden hour light", "moonlit shadows", "studio softbox light",
        "flickering candlelight", "backlit silhouette", "underwater caustics",
        "stormy overcast light", "blinding spotlight", "warm hearth glow",
        "cold fluorescent buzz", "split lighting", "bioluminescent ambience",
        "sunset god rays", "dappled forest light", "lightning flash", "ember firelight",
        "cyan and magenta gels", "foggy diffusion", "harsh midday sun", "lantern glow",
        "starlight shimmer", "screen-lit faces", "deep cave darkness", "aurora curtains",
        "smoky bar light", "high-key bright", "low-key noir shadows",
        // ---- additional lighting ----
        "alien suns (dual)", "arc lamp glare", "blacklight reactive", "blood moon eclipse",
        "blue hour gradient", "bonfire flicker", "bridge underlight", "candle procession",
        "ceiling bounce", "cinematic 3-point", "clamshell lighting", "cloudy sky diffuse",
        "coffee shop window", "cross-polarized", "curtain diffused", "dashboard glow",
        "dawn chorus light", "dead pixel glare", "dentist lamp", "desert mirage shimmer",
        "digital projector", "disco ball specks", "dome skylight", "dusk purple fade",
        "electrical arc flash", "emergency strobe", "endless void", "exit sign red",
        "explosion fireball", "eyeball reflection", "fairy jar twinkle", "falling snow bounce",
        "far side of moon", "fiber optic tips", "flashbang whiteout", "floodlight beam",
        "fluorescent tube flicker", "forgotten basement bulb", "frozen tundra sun",
        "full moon zenith", "gas lamp hiss", "ghost light (theatre)", "glacier blue interior",
        "greenhouse glass", "halogen work light", "handheld torch", "hazy sunrise",
        "headlight tunnel", "holiday string lights", "hologram scanner", "hover drone spotlight",
        "ice cave refractions", "infrared thermal glow", "ink darkness", "interrogation lamp",
        "jack-o-lantern grin", "jupiter storm reflection", "kaleidoscope mirrors",
        "lantern festival", "laptop screen dim", "laser trap lines", "lava tube glow",
        "library reading lamp", "lightning ball plasma", "lighthouse beacon",
        "living room TV flicker", "machinery warning light", "magma fissure", "market awning",
        "match strike flare", "mercury vapor hum", "midnight fog bank", "milk crate flashlight",
        "mining helmet beam", "mirror ball highlights", "mobile phone selfie", "moon halo",
        "neon cross reflection", "night vision green", "office cubicle glow", "oil rig flare",
        "operating theatre lamp", "oxygen arc torch", "paparazzi strobes", "parlor chandelier",
        "phone screen backlight", "phosphorescent paint", "pilot cockpit red", "pinhole camera",
        "pirate treasure chest", "police dash light", "porch swing dusk", "prison yard flood",
        "puddle reflection", "pulp magazine cover", "pumpkin interior", "quantum dot backlight",
        "radium dial green", "rain soaked street lamp", "rave laser array", "red light district",
        "refrigerator interior", "rescue flare", "restaurant neon open", "rock concert wash",
        "safety vest reflection", "sandstorm veiled sun", "satellite downlink flash",
        "sci-fi force field", "scuba dive beam", "seance candle ring", "searchlight sweep",
        "shaded porch", "shooting star streak", "shrine lantern row", "signal fire smoke",
        "skylight well", "slender man flashlight", "snow globe twinkle", "solar eclipse",
        "space station porthole", "sparkler trails", "spooky jack-o-lantern", "stage follow spot",
        "star projector", "steel mill glow", "submarine periscope", "sun through leaves",
        "sunburn studio", "swamp gas flame", "tactical flashlight", "tail light smear",
        "tent lantern", "theatre footlights", "thunderstorm flash", "tiki torch line",
        "tilt-shift miniature", "tinfoil reflector", "tombstone moonlight", "traffic jam red",
        "train headlight", "trampoline sun bounce", "trash fire", "tunnel exit flare",
        "ultraviolet sterilizer", "umbrella shadow", "under-bed glow", "underground lake",
        "unstable plasma", "van de graaff spark", "vending machine backlight", "video call window",
        "volcano eruption red", "vomiting strobe", "wagon train campfire", "walkway solar disc",
        "warehouse bay light", "warm soda machine", "water ripple reflection",
        "welding arc blue", "werewolf moon", "wet asphalt glow", "whale fall abyss",
        "wheat field sunset", "windshield glare", "winter solstice", "x-ray backscatter",
        "xenon headlight", "yacht cabin warm", "yeti cave ice", "zebra crossing light",
        "zen garden dawn", "zero g floating dust", "zombie apocalypse haze"
    ],
    palette: [
        "muted earth tones", "vibrant neon", "monochrome", "pastel gradient",
        "high-contrast noir", "warm sunset hues", "cool teal and orange",
        "iridescent jewel tones", "washed-out sepia", "acid green and black",
        "blood red and ivory", "icy blues", "autumn rust and gold", "candy pop colors",
        "deep ocean blues", "desert ochre", "royal purple and gold", "ashen grays",
        "electric cyber blues", "forest greens", "rose and copper", "stark black and white",
        "toxic yellow and purple", "soft lavender mist", "burnt orange and teal",
        "frozen white and silver", "volcanic red and charcoal", "emerald and brass",
        "dusty rose", "midnight indigo",
        // ---- additional palettes ----
        "amber and obsidian", "amethyst and jade", "apricot and cream", "arctic camouflage",
        "army fatigue green", "aubergine and lime", "azure and coral", "bamboo and slate",
        "beetroot and gold", "bismuth rainbow", "black metal and rust", "blush and pearl",
        "brick and mortar", "burgundy and blush", "buttercup and honey", "cadmium red and zinc",
        "camo green and khaki", "canary and graphite", "carnelian and onyx", "celadon and amber",
        "cerulean and gold", "chalk pastel brights", "champagne and charcoal", "cherry and cream",
        "chocolate and mint", "chromium and cobalt", "cinnabar and turquoise", "citrus zest pack",
        "clay and straw", "coal and flame", "cobalt and amber", "coffee and caramel",
        "copper verdigris", "crimson and bone", "cyanotype blue", "denim and brass",
        "desert sunrise", "dijon and wine", "eggplant and saffron", "electric lavender",
        "emerald and ruby", "fir and frost", "flamingo and tangerine", "flint and steel",
        "fluorite spectrum", "fuchsia and teal", "ginger and sand", "glass and chrome",
        "glossy magenta", "grape and olive", "gunmetal and copper", "hazel and moss",
        "heather and silver", "holo glitter", "honey and rust", "hot pink and cyan",
        "indanthrone blue", "ink and parchment", "jasmine and sage", "jet black and gold",
        "juniper and snow", "lavender and charcoal", "lemon and sterling", "lichen and bark",
        "lilac and lead", "limewash white", "loganberry and cream", "macaron mix",
        "malachite and pearl", "mango and chili", "marine blue and sand", "mars red and basalt",
        "matcha and cream", "merlot and rose gold", "milk chocolate", "mint chip",
        "moonstone and onyx", "mulberry and chalk", "mustard and pickle", "nectar and moss",
        "neon pastel blast", "nickel and silver", "nightshade purple", "oceanic black",
        "ochre and lapis", "olive and khaki", "opal drift", "orange crush and violet",
        "orchid and ash", "oxide red and brass", "pacific blue", "papyrus and ink",
        "peach and cream", "periwinkle and dove", "persimmon and pewter", "pine and steel",
        "pistachio and cream", "platinum and blush", "plum and charcoal", "pomegranate and bronze",
        "poppy and slate", "porcelain white", "prussian blue", "pumpkin and moss",
        "purple iris and gold", "quartz and rose", "raspberry and cream", "raven and silver",
        "rhubarb and custard", "rose gold and blush", "royal blue and ivory", "ruby and onyx",
        "saffron and indigo", "sakura and steel", "salmon and sage", "sand dollar",
        "sangria and gold", "sapphire and brass", "scarlet and charcoal", "sea glass pastels",
        "seafoam and pearl", "sepia and bone", "shamrock and cream", "sienna and slate",
        "silver and ash", "sky blue and cream", "slate and rose", "smoke and mirrors",
        "smoky quartz", "snow and charcoal", "soft cherry blossom", "spiced rum and tan",
        "spring crocus", "star sapphire", "steel and rust", "strawberry milk",
        "sugar plum and cream", "sun bleached bones", "sunflower and moss", "tangerine and lilac",
        "taupe and ivory", "tea stain brown", "terracotta and cream", "thistle and heather",
        "thulian pink", "tiger eye and jet", "topaz and cobalt", "tropical lagoon",
        "truffle and cream", "tulip red and ivory", "turquoise and copper", "umber and gold",
        "vanilla and espresso", "vermillion and jet", "violet and amber", "viridian and silver",
        "volcanic pumice", "water lily pastels", "wenge and cream", "whipped cream",
        "wild berry and cream", "wine and gold", "wintergreen and silver", "wisteria and pearl",
        "xanthic and slate", "xyloid (wood tones)", "yarrow and dusky", "yellowcake and charcoal",
        "yolk and shell", "zebrawood and ebony", "zinc white and indigo", "zircon and pearl"
    ]
};