export interface SoulHistoryEntry {
  id: string;
  action: 'MANIFESTED' | 'TRADED' | 'BANK_RESTOCKED' | 'GRANTED_BY_DEALER' | 'MODIFIED' | 'BURN_PROCESSED' | 'TRADE_PROPOSED' | 'TRADE_REJECTED';
  actionType?: string; // Support frontend field names
  timestamp: string;
  fromOwner: string;
  byNickname?: string; // Support frontend field names (who conducted/started)
  toOwner: string;
  recipientNickname?: string; // Support frontend field names (who received)
  details: string;
  reason?: string; // Why did this lifecycle event occur (trade reason / burn reason)
}

export interface Soul {
  id: string;
  owner: string; // Current owner nickname
  originalOwner: string; // Nickname of the creator
  name: string; // Poetic name, e.g. "Aura of the Abyssal Tide"
  archetype: 'Celestial' | 'Abyssal' | 'Chronos' | 'Verdant' | 'Stardust' | 'Infernal' | 'Void';
  alignment: string; // e.g., "Chaotic Neutral", "Lawful Good"
  purity: number; // 0 to 100
  weight: number; // Spiritual burden/weight (grams or mystical units)
  power: number; // Spark Level / Power index
  description: string; // A deep, poetic summary written by the cosmic force
  theme: string; // Visual aesthetic preset (Tailwind from-to gradients + colors)
  createdAt: string;
  isCustom: boolean; // Was it generated by a real human player?
  isFaux?: boolean; // Is it an artificial or replicated soul?
  soulType?: 'Original' | 'New' | 'Faux' | 'Inherited'; // Soul category tag
  history?: SoulHistoryEntry[]; // Historical record of owners and trades
}

export type TradeStatus = 'PENDING' | 'ACCEPTED' | 'DECLINED';

export interface TradeOffer {
  id: string;
  senderName: string; // Who sent the proposal
  senderSoulId: string; // Soul they are offering
  senderSoulName: string; // Cache for display
  receiverName: string; // Whose soul is being targetted
  receiverSoulId: string; // Soul they want to acquire
  receiverSoulName: string; // Cache for display
  status: TradeStatus;
  reason: string; // Required trade explanation
  responseMessage?: string; // e.g., Reason for decline/acceptance
  createdAt: string;
}

export interface TradeLog {
  id: string;
  senderName: string;
  receiverName: string;
  offeredSoulName: string;
  receivedSoulName: string;
  timestamp: string;
}

export interface QuizQuestion {
  id: number;
  text: string;
  options: {
    text: string;
    affinity: 'Celestial' | 'Abyssal' | 'Chronos' | 'Verdant' | 'Stardust' | 'Infernal' | 'Void';
    valueEffects: { purity: number; power: number; weight: number };
  }[];
}

export interface ManifestRequest {
  nickname: string;
  quizAnswers: { questionId: number; selectedOptionIndex: number }[];
}

export interface ManifestResponse {
  soul: Soul;
}
